json.id recipe.id
json.title recipe.title
json.chef recipe.chef
json.prep_time recipe.prep_time
json.image_url recipe.image_url
json.ingredients recipe.ingredients
json.ingredients_list recipe.ingredients_list
json.directions recipe.directions
json.directions_list recipe.directions_list
json.created_at recipe.created_at
json.updated_at recipe.updated_at